# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='lyy', max_length=100)),
                ('content', models.TextField(default='This is a excellent blog.')),
            ],
        ),
    ]
